image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

before_script:
  - 'gradle -v'

stages:
  - test
  - build

test:
  stage: test
  script: gradle test --no-daemon --stacktrace

build:
  stage: build
  script: gradle build --no-daemon --stacktrace
