image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

tags:
  - linux

stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq openjdk-17-jdk gradle

build:
  stage: build
  script: gradle assemble

test:
  stage: test
  script: gradle check
