image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

before_script:
  - chmod +x gradlew
  - 'wget -q https://services.gradle.org/distributions/gradle-8.6-bin.zip'
  - 'unzip -qq gradle-8.6-bin.zip'
  - 'export PATH=$PWD/gradle-8.6/bin:$PATH'
  - 'echo "PATH=$PATH"'
  - 'gradle -v'

stages:
  - test
  - build

test:
  stage: test
  script: ./gradlew test --no-daemon --stacktrace

build:
  stage: build
  script: ./gradlew build --no-daemon --stacktrace
