image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - config
  - build
  - test

config:
  stage: config
  script: gradle -v
  tags:
    - linux

build:
  stage: build
  script: gradle assemble --stacktrace
  tags:
    - linux

test:
  stage: test
  script: gradle check --stacktrace
  tags:
    - linux
