image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

before_script:
  - chmod +x ./gradlew

stages:
  - config
  - build
  - test

config:
  stage: config
  script: ./gradlew -v
  tags:
    - linux

build:
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
  tags:
    - linux

test:
  stage: test
  script: ./gradlew test
  tags:
    - linux
