image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

before_script:
  - chmod +x gradlew

stages:
  - test
  - build

test:
  stage: test
  script: ./gradlew test --no-daemon --stacktrace
  tags:
    - linux

build:
  stage: build
  script: ./gradlew build --no-daemon --stacktrace
  tags:
    - linux
