image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

stages:
  - test
  - build

test:
  image: gradle:jdk17
  stage: test
  script: gradle test --no-daemon --stacktrace
  tags:
    - linux

build:
  image: gradle:jdk17
  stage: build
  script: gradle build --no-daemon --stacktrace
  tags:
    - linux
