image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - setup
  - dependencies
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

setup:
  stage: setup
  script:
    - apt-get update -qq && apt-get install -y -qq gradle
  tags:
    - linux

dependencies:
  stage: dependencies
  script: ./gradlew dependencies
  tags:
    - linux

build:
  stage: build
  script: ./gradlew assemble
  tags:
    - linux
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script: ./gradlew check
  tags:
    - linux
