image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

stages:
  - config
  - build
  - test

config:
  stage: config
  script: gradle -v
  tags:
    - linux

build:
  stage: build
  script:
    - gradle clean
    - gradle assemble --stacktrace
  tags:
    - linux

test:
  stage: test
  script: gradle check --stacktrace
  tags:
    - linux
